[toolchain]
profile = "minimal"

# 1.79 nightly will cause a build error of num-bigint crate, so use 1.77 instead
# for more info refer to <https://forge.rust-lang.org/>
channel = "nightly-2024-01-18"
components = ["rust-src", "llvm-tools", "rustfmt", "clippy"]

# add windows target if you want
targets = ["x86_64-unknown-linux-gnu"]